server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://119.28.25.204:3306/test456?autoReconnect=true
    username: eric123
    password: yftYYYYMMDDHHmmssERIC123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    timeout: 10000ms
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect