server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://119.28.25.204:3306/test456?autoReconnect=true
    username: eric123
    password: yftYYYYMMDDHHmmssERIC123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    timeout: 10000ms
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  quartz:
    # 参见 org.springframework.boot.autoconfigure.quartz.QuartzProperties
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
    scheduler-name: penstoneScheduler
    properties:
      org.quartz.threadPool.threadCount: 5
      org.quartz.threadPool.threadPriority: 5
      org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread: true
      org.quartz.jobStore.misfireThreshold: 5000
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      # 在调度流程的第一步，也就是拉取待即将触发的triggers时，是上锁的状态，即不会同时存在多个线程拉取到相同的trigger的情况，也就避免的重复调度的危险。参考：https://segmentfault.com/a/1190000015492260
      org.quartz.jobStore.acquireTriggersWithinLock: true
  logging:
    level:
      NewPenstone: debug
      com.xkcoding.task.quartz.mapper: trace
  mybatis:
    configuration:
      # 下划线转驼峰
      map-underscore-to-camel-case: true
      mapper-locations: classpath:mappers/*.xml
      type-aliases-package: com.xkcoding.task.quartz.entity
  mapper:
    mappers:
      - tk.mybatis.mapper.common.Mapper
    not-empty: true
    style: camelhump
    wrap-keyword: "`{0}`"
    safe-delete: true
    safe-update: true
    identity: MYSQL
  pagehelper:
    auto-dialect: true
    helper-dialect: mysql
    reasonable: true
    params: count=countSql